// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBevCjO2A8sKXHVI0q8BsMA6oXC3DsrKBA',
    appId: '1:767933880284:android:2b99beb122f1c799c56119',
    messagingSenderId: '767933880284',
    projectId: 'luna-group-fae54',
    storageBucket: 'luna-group-fae54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfE2AIdZqySMwHL30tZe4KNDesC5KEhhk',
    appId: '1:767933880284:ios:c306f108578dca5ac56119',
    messagingSenderId: '767933880284',
    projectId: 'luna-group-fae54',
    storageBucket: 'luna-group-fae54.appspot.com',
    iosClientId: '767933880284-01nvkn851k6r9v3pj5sn71qcq99r4sfs.apps.googleusercontent.com',
    iosBundleId: 'com.facesdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfE2AIdZqySMwHL30tZe4KNDesC5KEhhk',
    appId: '1:767933880284:ios:5d3b2a8cb485e3d0c56119',
    messagingSenderId: '767933880284',
    projectId: 'luna-group-fae54',
    storageBucket: 'luna-group-fae54.appspot.com',
    iosClientId: '767933880284-gn66t8fbdeqt6pthgcnujjpt97r0tv44.apps.googleusercontent.com',
    iosBundleId: 'com.nightclub.clubApp.clubApp',
  );
}
